language : node_js
node_js: stable

deploy:
  provider: npm
  email: kingdream90@163.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    branch: master
  tag: latest   
  condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'