jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: stable
      deploy:
        provider: npm
        email: "kingdream90@163.com"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true